import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/theme';

export const roomStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.dark.background },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderBottomColor: Colors.dark.backgroundElement },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: Colors.dark.text },
  backText: { color: Colors.dark.danger, fontSize: 16, fontWeight: 'bold' },
  settingsText: { fontSize: 20 },
  subHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 15, paddingTop: 10 },
  subHeaderLink: { color: Colors.dark.primary, fontWeight: 'bold', fontSize: 14 },
  locationBanner: { color: Colors.dark.textSecondary, textAlign: 'center', paddingVertical: 6, fontSize: 12 },
  roomErrorText: { color: Colors.dark.danger, textAlign: 'center', paddingVertical: 8, fontSize: 13, fontWeight: 'bold' },
  nowPlayingCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.dark.backgroundElement, margin: 15, marginBottom: 0, padding: 12, borderRadius: 12 },
  nowPlayingCover: { width: 56, height: 56, borderRadius: 8, marginRight: 12, backgroundColor: Colors.dark.backgroundSelected },
  nowPlayingLabel: { color: Colors.dark.primary, fontSize: 11, fontWeight: 'bold', marginBottom: 2, textTransform: 'uppercase' },
  nowPlayingTitle: { color: Colors.dark.text, fontSize: 16, fontWeight: 'bold' },
  nowPlayingArtist: { color: Colors.dark.textSecondary, fontSize: 13, marginBottom: 6 },
  progressBarTrack: { height: 3, backgroundColor: Colors.dark.backgroundSelected, borderRadius: 2, overflow: 'hidden' },
  progressBarFill: { height: 3, backgroundColor: Colors.dark.primary },
  playPauseButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.dark.primary, justifyContent: 'center', alignItems: 'center', marginLeft: 10 },
  playPauseIcon: { fontSize: 16, color: Colors.dark.background },
  volumeBtn: { fontSize: 16 },
  searchContainer: { padding: 15, backgroundColor: Colors.dark.background },
  searchInput: { backgroundColor: Colors.dark.backgroundElement, color: Colors.dark.text, padding: 15, borderRadius: 12, fontSize: 16 },
  content: { flex: 1, paddingHorizontal: 15 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: Colors.dark.text, marginBottom: 15 },
  trackCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.dark.backgroundElement, padding: 10, borderRadius: 10, marginBottom: 10 },
  albumCover: { width: 50, height: 50, borderRadius: 8, marginRight: 15, backgroundColor: Colors.dark.backgroundSelected },
  trackInfo: { flex: 1 },
  trackTitle: { color: Colors.dark.text, fontSize: 16, fontWeight: 'bold', marginBottom: 4 },
  trackArtist: { color: Colors.dark.textSecondary, fontSize: 14, marginBottom: 4 },
  addButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.dark.primary, justifyContent: 'center', alignItems: 'center', marginLeft: 10 },
  addButtonDisabled: { backgroundColor: Colors.dark.backgroundSelected },
  addButtonText: { color: Colors.dark.background, fontSize: 24, fontWeight: 'bold', lineHeight: 26 },
  emptyQueueText: { color: Colors.dark.textSecondary, fontSize: 14, textAlign: 'center', marginTop: 40 },
  voteContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.dark.background, borderRadius: 20, paddingHorizontal: 5 },
  voteBtn: { padding: 8 },
  voteIcon: { fontSize: 16, opacity: 0.4 },
  voteIconActive: { opacity: 1 },
  voteCount: { color: Colors.dark.text, fontWeight: 'bold', fontSize: 16, marginHorizontal: 5, minWidth: 20, textAlign: 'center' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  modalCard: { backgroundColor: Colors.dark.background, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, maxHeight: '75%' },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: Colors.dark.text, marginBottom: 12 },
  modalSubtitle: { fontSize: 14, color: Colors.dark.textSecondary, marginBottom: 20 },
  modalCloseButton: { marginTop: 16, alignItems: 'center' },
  forgotPasswordTextBtn: { color: Colors.dark.primary, fontSize: 14, fontWeight: 'bold' },
  friendInviteRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: Colors.dark.backgroundElement, padding: 14, borderRadius: 10, marginBottom: 10 },
  memberRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: Colors.dark.backgroundElement, padding: 14, borderRadius: 10, marginBottom: 10 },
  acceptButton: { backgroundColor: Colors.dark.primary, paddingVertical: 8, paddingHorizontal: 14, borderRadius: 16 },
  acceptButtonText: { color: Colors.dark.background, fontWeight: 'bold', fontSize: 12 },
  declineButton: { backgroundColor: Colors.dark.backgroundSelected, paddingVertical: 8, paddingHorizontal: 14, borderRadius: 16 },
  declineButtonText: { color: Colors.dark.text, fontWeight: 'bold', fontSize: 12 },
  friendBadge: { backgroundColor: 'rgba(29, 185, 84, 0.15)', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 12, alignSelf: 'flex-start', marginTop: 6 },
  friendBadgeText: { color: Colors.dark.primary, fontWeight: 'bold', fontSize: 12 },
  message: { color: Colors.dark.primary, fontSize: 13, fontWeight: 'bold', marginTop: 10 },
  confirmLeaveButton: { backgroundColor: Colors.dark.danger, paddingVertical: 16, borderRadius: 50, alignItems: 'center' },
  confirmLeaveButtonText: { color: '#FFF', fontWeight: 'bold', fontSize: 16, letterSpacing: 1 },
});