import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/theme';

export const roomStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.dark.background },
  subHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 15, paddingTop: 10 },
  subHeaderLink: { color: Colors.dark.primary, fontWeight: 'bold', fontSize: 14 },
  licenseBanner: { color: Colors.dark.textSecondary, textAlign: 'center', paddingHorizontal: 15, paddingTop: 8, fontSize: 12, lineHeight: 17 },
  statusText: { color: Colors.dark.textSecondary, textAlign: 'center', paddingTop: 8, fontSize: 12 },
  toast: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 24,
    backgroundColor: Colors.dark.backgroundSelected,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  toastText: { color: Colors.dark.text, textAlign: 'center', fontWeight: 'bold', fontSize: 14 },

  nowPlayingCard: { backgroundColor: Colors.dark.backgroundElement, margin: 15, marginBottom: 0, padding: 12, borderRadius: 12 },
  nowPlayingRow: { flexDirection: 'row', alignItems: 'center' },
  nowPlayingCover: { width: 56, height: 56, borderRadius: 8, marginRight: 12, backgroundColor: Colors.dark.backgroundSelected },
  nowPlayingLabel: { color: Colors.dark.primary, fontSize: 12, fontWeight: 'bold', marginBottom: 2 },
  nowPlayingTitle: { color: Colors.dark.text, fontSize: 16, fontWeight: 'bold' },
  nowPlayingArtist: { color: Colors.dark.textSecondary, fontSize: 13, marginBottom: 6 },
  nowPlayingIdle: { color: Colors.dark.textSecondary, fontSize: 14, paddingVertical: 8 },
  progressBarTrack: { height: 3, backgroundColor: Colors.dark.backgroundSelected, borderRadius: 2, overflow: 'hidden' },
  progressBarFill: { height: 3, backgroundColor: Colors.dark.primary },
  timeRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 },
  timeText: { color: Colors.dark.textSecondary, fontSize: 11 },
  controlsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 },
  controlsGroup: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  listenButton: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 16, backgroundColor: Colors.dark.backgroundSelected },
  listenButtonActive: { backgroundColor: 'rgba(29, 185, 84, 0.2)' },
  listenText: { color: Colors.dark.textSecondary, fontWeight: 'bold', fontSize: 12 },
  listenTextActive: { color: Colors.dark.primary },
  playPauseButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.dark.primary, justifyContent: 'center', alignItems: 'center' },
  roundButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: Colors.dark.backgroundSelected, justifyContent: 'center', alignItems: 'center' },
  roundButtonText: { color: Colors.dark.text, fontSize: 18, fontWeight: 'bold', lineHeight: 20 },
  playTriangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 7,
    borderBottomWidth: 7,
    borderLeftWidth: 11,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: Colors.dark.background,
    marginLeft: 2,
  },
  pauseIconRow: { flexDirection: 'row', gap: 4 },
  pauseBar: { width: 4, height: 14, backgroundColor: Colors.dark.background, borderRadius: 1 },
  nextIconRow: { flexDirection: 'row', alignItems: 'center' },
  nextTriangle: {
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderTopWidth: 6,
    borderBottomWidth: 6,
    borderLeftWidth: 8,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: Colors.dark.text,
  },
  nextBar: { width: 2, height: 12, backgroundColor: Colors.dark.text, marginLeft: 1 },
  volumeText: { color: Colors.dark.textSecondary, fontSize: 12, minWidth: 36, textAlign: 'center' },
  delegateNote: { color: Colors.dark.primary, fontSize: 12, marginTop: 10 },

  searchContainer: { padding: 15, backgroundColor: Colors.dark.background },
  searchInput: { backgroundColor: Colors.dark.backgroundElement, color: Colors.dark.text, padding: 15, borderRadius: 12, fontSize: 16 },
  content: { flex: 1, paddingHorizontal: 15 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: Colors.dark.text, marginBottom: 15 },
  trackCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.dark.backgroundElement, padding: 10, borderRadius: 10, marginBottom: 10 },
  albumCover: { width: 50, height: 50, borderRadius: 8, marginRight: 15, backgroundColor: Colors.dark.backgroundSelected },
  trackInfo: { flex: 1 },
  trackTitle: { color: Colors.dark.text, fontSize: 16, fontWeight: 'bold', marginBottom: 4 },
  trackArtist: { color: Colors.dark.textSecondary, fontSize: 14, marginBottom: 2 },
  trackMeta: { color: Colors.dark.textSecondary, fontSize: 12 },
  addButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.dark.primary, justifyContent: 'center', alignItems: 'center', marginLeft: 10 },
  addButtonDisabled: { backgroundColor: Colors.dark.backgroundSelected },
  addButtonText: { color: Colors.dark.background, fontSize: 24, fontWeight: 'bold', lineHeight: 26 },
  emptyQueueText: { color: Colors.dark.textSecondary, fontSize: 14, textAlign: 'center', marginTop: 40, lineHeight: 20 },
  voteContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.dark.background, borderRadius: 20, paddingHorizontal: 5 },
  voteBtn: { padding: 8 },
  voteIcon: { fontSize: 16, opacity: 0.4 },
  voteIconActive: { opacity: 1 },
  voteCount: { color: Colors.dark.text, fontWeight: 'bold', fontSize: 16, marginHorizontal: 5, minWidth: 20, textAlign: 'center' },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  modalCard: { backgroundColor: Colors.dark.background, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, paddingBottom: 36, maxHeight: '80%' },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: Colors.dark.text, marginBottom: 12 },
  modalSubtitle: { fontSize: 14, color: Colors.dark.textSecondary, marginBottom: 20, lineHeight: 20 },
  modalSection: { fontSize: 15, fontWeight: 'bold', color: Colors.dark.text, marginTop: 8, marginBottom: 10 },
  modalCloseButton: { marginTop: 16, alignItems: 'center', paddingVertical: 8 },
  modalCloseText: { color: Colors.dark.primary, fontSize: 15, fontWeight: 'bold' },
  memberRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: Colors.dark.backgroundElement, padding: 14, borderRadius: 10, marginBottom: 10 },
  memberName: { color: Colors.dark.text, fontSize: 15, fontWeight: 'bold' },
  memberDevice: { color: Colors.dark.textSecondary, fontSize: 12, marginTop: 2 },
  acceptButton: { backgroundColor: Colors.dark.primary, paddingVertical: 8, paddingHorizontal: 14, borderRadius: 16 },
  acceptButtonText: { color: Colors.dark.background, fontWeight: 'bold', fontSize: 12 },
  declineButton: { backgroundColor: Colors.dark.backgroundSelected, paddingVertical: 8, paddingHorizontal: 14, borderRadius: 16 },
  declineButtonText: { color: Colors.dark.text, fontWeight: 'bold', fontSize: 12 },
  friendBadge: { backgroundColor: 'rgba(29, 185, 84, 0.15)', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 12, alignSelf: 'flex-start', marginTop: 6 },
  friendBadgeText: { color: Colors.dark.primary, fontWeight: 'bold', fontSize: 12 },
  profileLine: { color: Colors.dark.textSecondary, fontSize: 15, marginBottom: 6 },
  message: { color: Colors.dark.primary, fontSize: 13, fontWeight: 'bold', marginTop: 10 },
  confirmLeaveButton: { backgroundColor: Colors.dark.primary, paddingVertical: 16, borderRadius: 50, alignItems: 'center', marginBottom: 12 },
  confirmLeaveButtonText: { color: Colors.dark.background, fontWeight: 'bold', fontSize: 16 },
  deleteRoomButton: { backgroundColor: Colors.dark.danger, paddingVertical: 16, borderRadius: 50, alignItems: 'center' },
  deleteRoomButtonText: { color: '#FFF', fontWeight: 'bold', fontSize: 16 },
});
