import { StyleSheet } from 'react-native';
import { Border, Colors, Layout, Outline, Radius, Shadow, Space, Tones, Type } from '@/constants/theme';
import { ui } from '@/constants/styles';

const C = Colors.retro;

/** Room screen styles, built only from the tokens in theme.ts (and the shared `ui` styles). */
export const roomStyles = StyleSheet.create({
  container: ui.screen,
  subHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: Layout.gutter, paddingTop: Space.sm },
  subHeaderLink: ui.linkText,
  licenseBanner: { ...Type.small, color: C.textSecondary, textAlign: 'center', paddingHorizontal: Layout.gutter, paddingTop: Space.sm },
  statusText: { ...Type.small, color: C.textSecondary, textAlign: 'center', paddingTop: Space.sm },
  toast: {
    position: 'absolute',
    left: Layout.gutter,
    right: Layout.gutter,
    bottom: Space.xxl,
    backgroundColor: Tones.yellow.background,
    ...Outline,
    ...Shadow.md,
    borderRadius: Radius.md,
    paddingVertical: Space.md,
    paddingHorizontal: Space.lg,
  },
  toastText: { ...Type.label, color: Tones.yellow.foreground, textAlign: 'center' },

  // Now playing (violet card)
  nowPlayingCard: {
    backgroundColor: Tones.violet.background,
    ...Outline,
    ...Shadow.md,
    marginHorizontal: Layout.gutter,
    marginTop: Space.md,
    padding: Space.md + 2,
    borderRadius: Radius.xl,
  },
  nowPlayingRow: { flexDirection: 'row', alignItems: 'center' },
  nowPlayingCover: { width: 64, height: 64, borderRadius: Radius.md, marginRight: Space.md + 2, backgroundColor: C.backgroundSelected, ...Outline },
  nowPlayingLabel: { ...Type.small, color: C.accent, textTransform: 'uppercase', marginBottom: Space.xxs },
  nowPlayingTitle: { ...Type.label, fontSize: 16, lineHeight: 22, color: Tones.violet.foreground },
  nowPlayingArtist: { ...Type.small, fontSize: 13, color: Tones.violet.foreground, opacity: 0.85, marginBottom: Space.sm },
  nowPlayingIdle: { ...Type.body, fontSize: 14, color: Tones.violet.foreground, paddingVertical: Space.sm },
  progressBarTrack: { height: 10, backgroundColor: C.background, borderWidth: Border.thin, borderColor: C.ink, borderRadius: 6, overflow: 'hidden' },
  progressBarFill: { height: '100%', backgroundColor: C.accent },
  timeRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: Space.xs },
  timeText: { ...Type.small, fontSize: 11, color: Tones.violet.foreground, opacity: 0.85 },
  controlsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: Space.md, gap: Space.sm, flexWrap: 'wrap' },
  controlsGroup: { flexDirection: 'row', alignItems: 'center', gap: Space.sm + 2 },
  listenButton: {
    paddingVertical: Space.sm - 1,
    paddingHorizontal: Space.md,
    borderRadius: Radius.pill,
    backgroundColor: Tones.default.background,
    borderWidth: Border.thin,
    borderColor: C.ink,
    ...Shadow.sm,
  },
  listenButtonActive: { backgroundColor: Tones.green.background },
  listenRow: { flexDirection: 'row', alignItems: 'center', gap: Space.xs + 2 },
  listenText: { ...Type.buttonSmall, color: C.text },
  listenTextActive: { color: Tones.green.foreground },
  playPauseButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: Tones.yellow.background,
    ...Outline,
    ...Shadow.sm,
    justifyContent: 'center',
    alignItems: 'center',
  },
  roundButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Tones.default.background,
    borderWidth: Border.thin,
    borderColor: C.ink,
    justifyContent: 'center',
    alignItems: 'center',
  },
  roundButtonText: { ...Type.heading, lineHeight: 20, color: C.text },
  playTriangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 7,
    borderBottomWidth: 7,
    borderLeftWidth: 11,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: C.ink,
    marginLeft: 2,
  },
  pauseIconRow: { flexDirection: 'row', gap: Space.xs },
  pauseBar: { width: 4, height: 14, backgroundColor: C.ink, borderRadius: 1 },
  nextIconRow: { flexDirection: 'row', alignItems: 'center' },
  nextTriangle: {
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderTopWidth: 6,
    borderBottomWidth: 6,
    borderLeftWidth: 8,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: C.ink,
  },
  nextBar: { width: 2, height: 12, backgroundColor: C.ink, marginLeft: 1 },
  volumeText: { ...Type.buttonSmall, color: Tones.violet.foreground, minWidth: 36, textAlign: 'center' },
  delegateNote: { ...Type.small, color: C.accent, marginTop: Space.sm + 2, textDecorationLine: 'underline' },

  // Search + lists
  searchContainer: { paddingHorizontal: Layout.gutter, paddingVertical: Space.lg },
  searchInput: ui.input,
  content: { flex: 1, paddingHorizontal: Layout.gutter },
  sectionTitle: { ...Type.heading, color: C.text, marginBottom: Space.md + 2 },
  trackCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.backgroundElement,
    ...Outline,
    ...Shadow.md,
    padding: Space.sm + 2,
    borderRadius: Radius.xl,
    marginBottom: Space.md + 2,
  },
  albumCover: { width: 52, height: 52, borderRadius: Radius.sm + 2, marginRight: Space.md, backgroundColor: C.backgroundSelected, ...Outline },
  trackInfo: { flex: 1 },
  trackTitle: { ...Type.label, fontSize: 15, lineHeight: 20, color: C.text, marginBottom: Space.xxs },
  trackArtist: { ...Type.small, fontSize: 13, color: C.textSecondary, marginBottom: Space.xxs },
  trackMeta: { ...Type.small, fontSize: 11, color: C.textSecondary },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Tones.coral.background,
    ...Outline,
    ...Shadow.sm,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: Space.sm + 2,
  },
  addButtonDisabled: { backgroundColor: C.backgroundSelected },
  addButtonText: { ...Type.title, lineHeight: 28, color: Tones.coral.foreground },
  emptyQueueText: { ...Type.body, fontSize: 14, color: C.textSecondary, textAlign: 'center', marginTop: Space.xxxl + Space.sm },
  voteContainer: { alignItems: 'center', gap: Space.xs, marginLeft: Space.sm },
  voteBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: Border.thin,
    borderColor: C.ink,
    backgroundColor: C.backgroundElement,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voteBtnUpActive: { backgroundColor: Tones.green.background },
  voteBtnDownActive: { backgroundColor: Tones.coral.background },
  voteCount: { ...Type.label, color: C.text, minWidth: 20, textAlign: 'center' },

  // Modals
  modalOverlay: ui.modalOverlay,
  modalCard: ui.modalCard,
  modalTitle: ui.modalTitle,
  modalSubtitle: { ...Type.body, fontSize: 14, lineHeight: 20, color: C.textSecondary, marginBottom: Space.xl },
  modalSection: { ...Type.label, fontSize: 15, color: C.text, marginTop: Space.sm, marginBottom: Space.sm + 2 },
  modalCloseButton: { marginTop: Space.lg, alignItems: 'center', paddingVertical: Space.sm },
  modalCloseText: ui.linkText,
  memberRow: { ...ui.row, padding: Space.md + 2 },
  memberName: { ...Type.label, fontSize: 15, color: C.text },
  memberDevice: { ...Type.small, color: C.textSecondary, marginTop: Space.xxs },
  acceptButton: { ...ui.smallButton, marginLeft: 0 },
  acceptButtonText: ui.smallButtonText,
  declineButton: { ...ui.smallButtonMuted, marginLeft: 0 },
  declineButtonText: ui.smallButtonMutedText,
  friendBadge: { ...ui.chip, backgroundColor: Tones.green.background, marginTop: Space.sm - 2, paddingVertical: Space.xs },
  friendBadgeText: ui.chipText,
  profileLine: { ...Type.body, color: C.textSecondary, marginBottom: Space.sm - 2 },
  message: { ...Type.label, fontSize: 13, color: C.successForeground, marginTop: Space.sm + 2 },
  confirmLeaveButton: { ...ui.primaryButton, marginTop: 0, marginBottom: Space.md },
  confirmLeaveButtonText: ui.primaryButtonText,
  deleteRoomButton: { ...ui.dangerButton, marginTop: 0 },
  deleteRoomButtonText: ui.dangerButtonText,
});
