import { StyleSheet } from 'react-native';
import { Colors } from './theme';

// Shared screen styles (forms, lists, buttons)
export const ui = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.dark.background },
  scroll: { padding: 20, paddingBottom: 48 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: Colors.dark.text, marginTop: 24, marginBottom: 12 },
  label: { color: Colors.dark.textSecondary, fontSize: 14, marginBottom: 6, marginTop: 12 },
  input: {
    backgroundColor: Colors.dark.backgroundElement,
    color: Colors.dark.text,
    paddingHorizontal: 15,
    paddingVertical: 14,
    borderRadius: 10,
    fontSize: 16,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  inputError: { borderColor: Colors.dark.danger },
  fieldError: { color: Colors.dark.danger, fontSize: 12, marginTop: 4 },
  helper: { color: Colors.dark.textSecondary, fontSize: 13, lineHeight: 18, marginTop: 6 },
  primaryButton: {
    backgroundColor: Colors.dark.primary,
    paddingVertical: 16,
    borderRadius: 50,
    alignItems: 'center',
    marginTop: 24,
  },
  primaryButtonText: { color: Colors.dark.background, fontSize: 16, fontWeight: 'bold' },
  secondaryButton: {
    backgroundColor: Colors.dark.backgroundSelected,
    paddingVertical: 14,
    borderRadius: 50,
    alignItems: 'center',
    marginTop: 12,
  },
  secondaryButtonText: { color: Colors.dark.text, fontSize: 15, fontWeight: 'bold' },
  dangerButton: { backgroundColor: Colors.dark.danger, paddingVertical: 14, borderRadius: 50, alignItems: 'center', marginTop: 12 },
  dangerButtonText: { color: '#FFF', fontSize: 15, fontWeight: 'bold' },
  disabled: { opacity: 0.5 },
  linkText: { color: Colors.dark.primary, fontWeight: 'bold', fontSize: 14 },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.dark.backgroundElement,
    padding: 14,
    borderRadius: 10,
    marginBottom: 10,
  },
  rowTitle: { color: Colors.dark.text, fontSize: 16, fontWeight: 'bold' },
  rowSubtitle: { color: Colors.dark.textSecondary, fontSize: 13, marginTop: 2 },
  smallButton: { backgroundColor: Colors.dark.primary, paddingVertical: 8, paddingHorizontal: 14, borderRadius: 16, marginLeft: 8 },
  smallButtonText: { color: Colors.dark.background, fontWeight: 'bold', fontSize: 12 },
  smallButtonMuted: { backgroundColor: Colors.dark.backgroundSelected, paddingVertical: 8, paddingHorizontal: 14, borderRadius: 16, marginLeft: 8 },
  smallButtonMutedText: { color: Colors.dark.text, fontWeight: 'bold', fontSize: 12 },
  empty: { color: Colors.dark.textSecondary, fontSize: 14, textAlign: 'center', marginTop: 24, lineHeight: 20 },
  messageSuccess: { color: Colors.dark.primary, fontWeight: 'bold', textAlign: 'center', marginTop: 12 },
  messageError: { color: Colors.dark.danger, fontWeight: 'bold', textAlign: 'center', marginTop: 12 },
  segment: { flexDirection: 'row', backgroundColor: Colors.dark.backgroundElement, borderRadius: 10, padding: 4 },
  segmentItem: { flex: 1, paddingVertical: 10, borderRadius: 8, alignItems: 'center' },
  segmentItemActive: { backgroundColor: Colors.dark.primary },
  segmentText: { color: Colors.dark.textSecondary, fontWeight: 'bold', fontSize: 13 },
  segmentTextActive: { color: Colors.dark.background },
});
