#!/usr/bin/env bash
# Generates backend/.env and frontend/.env from the root .env file.
# No templates needed: the script writes complete files.
# Usage: make env  (or ./scripts/setup-env.sh)
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

if [ ! -f .env ]; then
  echo "❌ Missing .env at project root."
  echo "    cp env.example .env  # then fill it in"
  exit 1
fi

# Load root .env
set -a
# shellcheck disable=SC1091
. ./.env
set +a

# --- Defaults ---
POSTGRES_USER="${POSTGRES_USER:-musicroom}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-motdepasse}"
POSTGRES_DB="${POSTGRES_DB:-musicroom}"
# Optional: set only when the API runs behind a reverse proxy
TRUST_PROXY="${TRUST_PROXY:-}"

# --- Auto-detect LAN IP ---
if [ -z "${LAN_IP:-}" ]; then
  if command -v hostname >/dev/null 2>&1 && hostname -I >/dev/null 2>&1; then
    LAN_IP=$(hostname -I | awk '{print $1}')
  elif command -v ipconfig >/dev/null 2>&1; then
    LAN_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)
  fi
fi
LAN_IP="${LAN_IP:-localhost}"

# --- JWT_SECRET ---
if [ -z "${JWT_SECRET:-}" ]; then
  JWT_SECRET=$(openssl rand -hex 32)
fi

# --- Required OAuth variables ---
: "${GOOGLE_CLIENT_ID:?GOOGLE_CLIENT_ID missing in root .env}"
: "${GOOGLE_CLIENT_SECRET:?GOOGLE_CLIENT_SECRET missing in root .env}"

DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}"
TEST_DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}_test"

# --- backend/.env ---
echo "→ Writing backend/.env"
cat > backend/.env <<EOF
# Generated by scripts/setup-env.sh — do not edit manually.
# Edit .env at the project root and re-run 'make env'.

PORT=3000
HOST=0.0.0.0
PUBLIC_URL=http://${LAN_IP}:3000
TRUST_PROXY=${TRUST_PROXY}

DATABASE_URL=${DATABASE_URL}
DB_POOL_MAX=20
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
TEST_DATABASE_URL=${TEST_DATABASE_URL}

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=7d

SMTP_HOST=
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASS=
MAIL_FROM="Music Room <no-reply@musicroom.local>"

RATE_LIMIT_DISABLED=

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
EOF

# --- frontend/.env ---
echo "→ Writing frontend/.env"
cat > frontend/.env <<EOF
# Generated by scripts/setup-env.sh — do not edit manually.
# Edit .env at the project root and re-run 'make env'.

EXPO_PUBLIC_API_URL=http://${LAN_IP}:3000
EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=${GOOGLE_CLIENT_ID}
EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID=
EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID=
EOF

echo ""
echo "✅ backend/.env and frontend/.env generated."
echo "   LAN_IP     : ${LAN_IP}"
echo "   API URL    : http://${LAN_IP}:3000"
echo "   DB         : ${POSTGRES_USER}@localhost:5432/${POSTGRES_DB}"
echo "   JWT_SECRET : ${JWT_SECRET:0:8}… (truncated)"
